<?xml version="1.0" encoding="utf-8"?><Database Name="CMSDatabase" Class="CMSDatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\CMSDatabase.mdf;Integrated Security=True" SettingsObjectName="Clinic_Management_System.My.MySettings" SettingsPropertyName="CMSDatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Employee" Member="Employees">
    <Type Name="Employee">
      <Column Name="EmployeeId" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="EmployeeType" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="IcNo" Type="System.String" DbType="VarChar(14)" CanBeNull="true" />
      <Column Name="Age" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="Gender" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ContactNo" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="EmailAdd" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="PostCode" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MedicalRecord" Member="MedicalRecords">
    <Type Name="MedicalRecord">
      <Column Name="RecordId" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PatientId" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="MedicalId" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="VisitDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BloodPressure" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="Allergies" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Disease" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Caution" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Payment" Member="Payments">
    <Type Name="Payment">
      <Column Name="PaymentId" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PayMethod" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="PaymentAmount" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PanelOrganisation" Member="PanelOrganisations">
    <Type Name="PanelOrganisation">
      <Column Name="PanelId" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="OrgName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="OrgCode" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CoverLimit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ContactNo" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="OrgNature" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Inventory" Member="Inventories">
    <Type Name="Inventory">
      <Column Name="ItemId" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ItemName" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ItemDescription" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="UnitPrice" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExpiryDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Patient" Member="Patients">
    <Type Name="Patient">
      <Column Name="PatientId" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="IcNo" Type="System.String" DbType="VarChar(14)" CanBeNull="true" />
      <Column Name="Age" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="ContactNo" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="EmailAdd" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="PostCode" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Invoice" Member="Invoices">
    <Type Name="Invoice">
      <Column Name="InvoiceId" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="InvoiceDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="InvoiceTime" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="PatientId" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="TotalPrice" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="PanelId" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="PaymentId" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="PaymentStatus" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Order]" Member="Orders">
    <Type Name="Order">
      <Column Name="OrderId" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="InvoiceId" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ItemId" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="AmountTaken" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Appointment" Member="Appointments">
    <Type Name="Appointment">
      <Column Name="AppointId" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PatientId" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="IcNo" Type="System.String" DbType="VarChar(14)" CanBeNull="true" />
      <Column Name="ContactNo" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="EmailAdd" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Time" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Medical" Member="Medicals">
    <Type Name="Medical">
      <Column Name="MedicalId" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PatientId" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ItemId" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="AmountTaken" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UpdateCheck" Member="UpdateChecks">
    <Type Name="UpdateCheck">
      <Column Name="UpdateCheckId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TableName" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="GotUpdate" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
    </Type>
  </Table>
</Database>